//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDocumentAPP.Context
{
    using Services;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PERSONA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERSONA()
        {
            this.EMPLEADOes = new HashSet<EMPLEADO>();
            this.TELEFONOes = new HashSet<TELEFONO>();
            this.RASTREO_EXPEDIENTE = new HashSet<RASTREO_EXPEDIENTE>();
        }

        [Required(ErrorMessage = "El nombre es requerido")]
        [Display(Name = "Nombre")]
        [RegularExpression(@"^[a-zA-Záéíóúñ''-'\s]{1,40}$", ErrorMessage = "Números y Caracteres especiales no son permitido en el Nombre.")]
        [StringLength(30, MinimumLength = 3, ErrorMessage = "La longitud debe ser entre 3 y 30")]
        public string NOMBRE { get; set; }

        [Required(ErrorMessage = "El Primer Apellido es requerido")]
        [Display(Name = "Primer Apellido")]
        [RegularExpression(@"^[a-zA-Záéíóúñ''-'\s]{1,40}$", ErrorMessage = "Numeros y Caracteres especiales no son permitido en el Primer Apellido.")]
        [StringLength(18, MinimumLength = 4, ErrorMessage = "La longitud debe ser entre 4 y 18")]
        public string PRIMER_APELLIDO { get; set; }

        [RegularExpression(@"^[a-zA-Záéíóúñ''-'\s]{1,40}$", ErrorMessage = "Numeros y Caracteres especiales no son permitido en el Segundo Apellido.")]
        [Display(Name = "Segundo Apellido")]
        [StringLength(18, MinimumLength = 4, ErrorMessage = "La longitud debe ser entre 4 y 18")]
        public string SEGUNDO_APELLIDO { get; set; }

        [Required(ErrorMessage = "El Tipo Identificación es requerido")]
        [Display(Name = "Tipo Identificación")]
        public string TIPO_IDENTIFICACION { get; set; }

        //  [Required(ErrorMessage = "La Identificación  es requerido")]
        [Display(Name = "Identificación")]
        //  [StringLength(11, MinimumLength = 11, ErrorMessage = "La longitud debe ser de 11")]
        [CustomIdentificacionValidator]
        public string IDENTIFICACION { get; set; }

        [Required(ErrorMessage = "El Sexo es requerido")]
        [Display(Name = "Sexo")]
        public string SEXO { get; set; }

        [Display(Name = "Correo")]
        [EmailAddress(ErrorMessage = "El Correo es Invalido")]
        public string EMAIL { get; set; }

        public string getPersonaDisplay()
        {
            return String.Format("{0} {1} - {2} ", NOMBRE, PRIMER_APELLIDO, IDENTIFICACION);
        }

       
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLEADO> EMPLEADOes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TELEFONO> TELEFONOes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RASTREO_EXPEDIENTE> RASTREO_EXPEDIENTE { get; set; }
    }
}
