//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDocumentAPP.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TELEFONO
    {
        public int TELEFONO_ID { get; set; }
        public int PERSONA_ID { get; set; }
        public string TIPO { get; set; }
        public string NUMERO { get; set; }
    
        public virtual PERSONA PERSONA { get; set; }
    }
}
