//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDocumentAPP.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLEADO()
        {
            this.DOCUMENTOes = new HashSet<DOCUMENTO>();
        }
    
        public int EMPLEADO_ID { get; set; }
        public int PERSONA_ID { get; set; }
        public string SUPERVISOR { get; set; }
        public int DEPENDENCIA_ID { get; set; }
        public string PUESTO { get; set; }
        public System.DateTime FECHA_INGRESO { get; set; }
        public decimal SUELDO { get; set; }
        public string BANCO { get; set; }
        public string CUENTABANCARIA { get; set; }
        public string EMPRESA { get; set; }
        public int ESTATUS_ID { get; set; }
    
        public virtual DEPENDENCIA DEPENDENCIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCUMENTO> DOCUMENTOes { get; set; }
        public virtual ESTATU ESTATU { get; set; }
        public virtual PERSONA PERSONA { get; set; }
    }
}
