//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDocumentAPP.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class PERSONA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERSONA()
        {
            this.EMPLEADOes = new HashSet<EMPLEADO>();
            this.TELEFONOes = new HashSet<TELEFONO>();
        }
    
        public int PERSONA_ID { get; set; }

        [Required(ErrorMessage = "El nombre es requerido")]
        [Display(Name = "Nombre Completo", Description = "xxxxx")]
        public string NOMBRE { get; set; }

        [Required(ErrorMessage = "El Primer Apellido es requerido")]
        [Display(Name = "Primer Apellido", Description = "xxxxx")]
        public string PRIMER_APELLIDO { get; set; }

        [Required(ErrorMessage = "El Segundo Apellido es requerido")]
        [Display(Name = "Segundo Apellido", Description = "xxxxx")]
        public string SEGUNDO_APELLIDO { get; set; }

        [Required(ErrorMessage = "El Tipo Identificacion es requerido")]
        [Display(Name = "Tipo Identificacion", Description = "xxxxx")]
        public string TIPO_IDENTIFICACION { get; set; }

        [Required(ErrorMessage = "La Identificacion  es requerido")]
        [Display(Name = "Identificacion", Description = "xxxxx")]
        public string IDENTIFICACION { get; set; }

        [Required(ErrorMessage = "El Sexo es requerido")]
        [Display(Name = "Sexo", Description = "xxxxx")]
        public string SEXO { get; set; }

        [Display(Name = "Correo", Description = "xxxxx")]
        public string EMAIL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLEADO> EMPLEADOes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TELEFONO> TELEFONOes { get; set; }
    }
}
